#include "Importer.h"

std::vector<Card> Importer::GetAllCards()
{
	return std::vector<Card>{
		Card(Color::Blue, CardAction::Zero),
		Card(Color::Blue, CardAction::One),
		Card(Color::Blue, CardAction::Two),
		Card(Color::Blue, CardAction::Three),
		Card(Color::Blue, CardAction::Four),
		Card(Color::Blue, CardAction::Five),
		Card(Color::Blue, CardAction::Six),
		Card(Color::Blue, CardAction::Seven),
		Card(Color::Blue, CardAction::Eight),
		Card(Color::Blue, CardAction::Nine),
		Card(Color::Blue, CardAction::PlusTwo),
		Card(Color::Blue, CardAction::Reverse),
		Card(Color::Blue, CardAction::Jump),

		Card(Color::Blue, CardAction::Zero),
		Card(Color::Blue, CardAction::One),
		Card(Color::Blue, CardAction::Two),
		Card(Color::Blue, CardAction::Three),
		Card(Color::Blue, CardAction::Four),
		Card(Color::Blue, CardAction::Five),
		Card(Color::Blue, CardAction::Six),
		Card(Color::Blue, CardAction::Seven),
		Card(Color::Blue, CardAction::Eight),
		Card(Color::Blue, CardAction::Nine),
		Card(Color::Blue, CardAction::PlusTwo),
		Card(Color::Blue, CardAction::Reverse),
		Card(Color::Blue, CardAction::Jump),

		Card(Color::Yellow, CardAction::Zero),
		Card(Color::Yellow, CardAction::One),
		Card(Color::Yellow, CardAction::Two),
		Card(Color::Yellow, CardAction::Three),
		Card(Color::Yellow, CardAction::Four),
		Card(Color::Yellow, CardAction::Five),
		Card(Color::Yellow, CardAction::Six),
		Card(Color::Yellow, CardAction::Seven),
		Card(Color::Yellow, CardAction::Eight),
		Card(Color::Yellow, CardAction::Nine),
		Card(Color::Yellow, CardAction::PlusTwo),
		Card(Color::Yellow, CardAction::Reverse),
		Card(Color::Yellow, CardAction::Jump),

		Card(Color::Yellow, CardAction::Zero),
		Card(Color::Yellow, CardAction::One),
		Card(Color::Yellow, CardAction::Two),
		Card(Color::Yellow, CardAction::Three),
		Card(Color::Yellow, CardAction::Four),
		Card(Color::Yellow, CardAction::Five),
		Card(Color::Yellow, CardAction::Six),
		Card(Color::Yellow, CardAction::Seven),
		Card(Color::Yellow, CardAction::Eight),
		Card(Color::Yellow, CardAction::Nine),
		Card(Color::Yellow, CardAction::PlusTwo),
		Card(Color::Yellow, CardAction::Reverse),
		Card(Color::Yellow, CardAction::Jump),

		Card(Color::Red, CardAction::Zero),
		Card(Color::Red, CardAction::One),
		Card(Color::Red, CardAction::Two),
		Card(Color::Red, CardAction::Three),
		Card(Color::Red, CardAction::Four),
		Card(Color::Red, CardAction::Five),
		Card(Color::Red, CardAction::Six),
		Card(Color::Red, CardAction::Seven),
		Card(Color::Red, CardAction::Eight),
		Card(Color::Red, CardAction::Nine),
		Card(Color::Red, CardAction::PlusTwo),
		Card(Color::Red, CardAction::Reverse),
		Card(Color::Red, CardAction::Jump),

		Card(Color::Red, CardAction::Zero),
		Card(Color::Red, CardAction::One),
		Card(Color::Red, CardAction::Two),
		Card(Color::Red, CardAction::Three),
		Card(Color::Red, CardAction::Four),
		Card(Color::Red, CardAction::Five),
		Card(Color::Red, CardAction::Six),
		Card(Color::Red, CardAction::Seven),
		Card(Color::Red, CardAction::Eight),
		Card(Color::Red, CardAction::Nine),
		Card(Color::Red, CardAction::PlusTwo),
		Card(Color::Red, CardAction::Reverse),
		Card(Color::Red, CardAction::Jump),

		Card(Color::Green, CardAction::Zero),
		Card(Color::Green, CardAction::One),
		Card(Color::Green, CardAction::Two),
		Card(Color::Green, CardAction::Three),
		Card(Color::Green, CardAction::Four),
		Card(Color::Green, CardAction::Five),
		Card(Color::Green, CardAction::Six),
		Card(Color::Green, CardAction::Seven),
		Card(Color::Green, CardAction::Eight),
		Card(Color::Green, CardAction::Nine),
		Card(Color::Green, CardAction::PlusTwo),
		Card(Color::Green, CardAction::Reverse),
		Card(Color::Green, CardAction::Jump),

		Card(Color::Green, CardAction::Zero),
		Card(Color::Green, CardAction::One),
		Card(Color::Green, CardAction::Two),
		Card(Color::Green, CardAction::Three),
		Card(Color::Green, CardAction::Four),
		Card(Color::Green, CardAction::Five),
		Card(Color::Green, CardAction::Six),
		Card(Color::Green, CardAction::Seven),
		Card(Color::Green, CardAction::Eight),
		Card(Color::Green, CardAction::Nine),
		Card(Color::Green, CardAction::PlusTwo),
		Card(Color::Green, CardAction::Reverse),
		Card(Color::Green, CardAction::Jump),

		Card(Color::Any, CardAction::PlusFour),
		Card(Color::Any, CardAction::PlusFour),
		Card(Color::Any, CardAction::PlusFour),
		Card(Color::Any, CardAction::PlusFour),

		Card(Color::Blue, CardAction::PlusTwoDiscard),
		Card(Color::Yellow, CardAction::PlusTwoDiscard),
		Card(Color::Red, CardAction::PlusTwoDiscard),
		Card(Color::Green, CardAction::PlusTwoDiscard),
	};
}
